import type {
  Cascade,
  CascadeNode,
  Flight,
  Recommendation,
  Rotation,
  Severity,
} from "@/lib/types";
import { CONGESTION } from "@/lib/mock/reference";
import { clamp, unitFromKey } from "@/lib/mock/rng";

/**
 * Beyond this depth the propagation model's correlation with observed delay
 * falls under 0.33 (see /performance). The UI must show a qualitative
 * statement rather than a number past this point.
 */
export const MODEL_CONFIDENCE_DEPTH = 2;

/** Mean fresh delay generated on a downstream leg, in minutes. */
export const EXPECTED_FRESH_DELAY_MIN = 11;

/* ------------------------------------------------------------------ */
/* Time helpers — ISO strings are local wall-clock, no timezone maths. */
/* ------------------------------------------------------------------ */

function isoToMinutes(iso: string): number {
  return Number(iso.slice(11, 13)) * 60 + Number(iso.slice(14, 16));
}

function minutesToIso(datePart: string, minutes: number): string {
  const m = ((minutes % 1440) + 1440) % 1440;
  const pad = (n: number) => (n < 10 ? `0${n}` : String(n));
  return `${datePart}T${pad(Math.floor(m / 60))}:${pad(m % 60)}:00`;
}

/* ------------------------------------------------------------------ */
/* Propagation                                                        */
/* ------------------------------------------------------------------ */

export function severityFor(totalDelayMin: number): Severity {
  if (totalDelayMin < 15) return "clear";
  if (totalDelayMin < 30) return "watch";
  if (totalDelayMin < 60) return "elevated";
  return "critical";
}

/**
 * Fresh delay generated by a leg itself: an ~11 minute expectation, modulated
 * by origin congestion and a stable per-flight offset.
 */
function freshDelayFor(flight: Flight): number {
  const congestion = CONGESTION[flight.origin] ?? 0.55;
  const congestionAdj = (congestion - 0.62) * 8;
  const jitter = unitFromKey(`fresh:${flight.id}`) * 6 - 3;
  return clamp(Math.round(EXPECTED_FRESH_DELAY_MIN + congestionAdj + jitter), 3, 22);
}

/**
 * The core cascade calculation.
 *
 *   inherited = max(0, inbound delay − available turnaround slack)
 *   total     = inherited + fresh delay on this leg
 *   interval  = total ± ~30%, widening one notch per hop
 *
 * The FastAPI backend replaces this entirely; the shape it returns is
 * `Cascade`, unchanged.
 */
export function computeCascade(
  rotation: Rotation,
  legIndex: number,
  observedDelayMin: number,
): Cascade {
  const originFlight =
    rotation.legs.find((l) => l.legIndex === legIndex) ?? rotation.legs[0];
  const downstream = rotation.legs.filter((l) => l.legIndex > originFlight.legIndex);

  const observed = Math.max(0, Math.round(observedDelayMin));
  let inbound = observed;
  const nodes: CascadeNode[] = [];

  downstream.forEach((flight, i) => {
    const hop = i + 1;
    const slackMin = flight.turnaroundSlackMin;
    const inheritedDelayMin = Math.max(0, inbound - slackMin);
    const freshDelayMin = freshDelayFor(flight);
    const totalDelayMin = inheritedDelayMin + freshDelayMin;
    const spread = 0.3 + 0.05 * (hop - 1);

    nodes.push({
      hop,
      flight,
      inboundDelayMin: inbound,
      slackMin,
      inheritedDelayMin,
      freshDelayMin,
      totalDelayMin,
      intervalLowMin: Math.max(0, Math.round(totalDelayMin * (1 - spread))),
      intervalHighMin: Math.round(totalDelayMin * (1 + spread)),
      absorbed: inheritedDelayMin === 0,
      severity: severityFor(totalDelayMin),
      quantitative: hop <= MODEL_CONFIDENCE_DEPTH,
    });

    inbound = totalDelayMin;
  });

  const quantitative = nodes.filter((n) => n.quantitative);

  return {
    originFlight,
    observedDelayMin: observed,
    nodes,
    totalDownstreamDelayMin: quantitative.reduce((sum, n) => sum + n.totalDelayMin, 0),
    legsAffected: nodes.filter((n) => n.totalDelayMin >= 15).length,
    confidenceDepth: MODEL_CONFIDENCE_DEPTH,
    recommendations: buildRecommendations(nodes, originFlight),
  };
}

/* ------------------------------------------------------------------ */
/* Recommendations                                                    */
/* ------------------------------------------------------------------ */

interface Trigger {
  category: Recommendation["category"];
  thresholdMin: number;
  /** How far ahead of departure the action has to be taken. */
  leadTimeMin: number;
  priority: Recommendation["priority"];
  title: (node: CascadeNode) => string;
  reason: (node: CascadeNode) => string;
}

const TRIGGERS: Trigger[] = [
  {
    category: "crew",
    thresholdMin: 25,
    leadTimeMin: 90,
    priority: "high",
    title: (n) => `Place reserve crew on standby at ${n.flight.origin}`,
    reason: (n) =>
      `A ${n.totalDelayMin} min departure pushes the duty period toward the legality limit; a standby crew costs far less than a cancellation.`,
  },
  {
    category: "catering",
    thresholdMin: 40,
    leadTimeMin: 55,
    priority: "medium",
    title: (n) => `Re-slot catering and fuelling for ${n.flight.flightNumber}`,
    reason: () =>
      "Ground handling booked against the original time will no-show and re-queue behind other turns, adding delay on top of delay.",
  },
  {
    category: "passenger",
    thresholdMin: 45,
    leadTimeMin: 75,
    priority: "medium",
    title: (n) => `Protect connections inbound to ${n.flight.destination}`,
    reason: (n) =>
      `Arrival slips past the ${n.flight.destination} connection bank; proactive rebooking now avoids overnight accommodation costs.`,
  },
  {
    category: "aircraft",
    thresholdMin: 60,
    leadTimeMin: 120,
    priority: "high",
    title: (n) => `Check reserve aircraft availability at ${n.flight.origin}`,
    reason: () =>
      "Above an hour the rotation is unlikely to recover unaided; a spare airframe breaks the chain instead of passing it on.",
  },
  {
    category: "slot",
    thresholdMin: 70,
    leadTimeMin: 45,
    priority: "high",
    title: (n) => `Renegotiate the departure slot at ${n.flight.origin}`,
    reason: () =>
      "Missing the assigned slot means going to the back of the queue; requesting a revised slot early is the cheapest minute you can buy.",
  },
];

/**
 * Recommendations are raised only from hops the model can quantify. Past the
 * confidence boundary we do not pretend to know enough to spend money.
 */
function buildRecommendations(nodes: CascadeNode[], origin: Flight): Recommendation[] {
  const datePart = origin.scheduledDeparture.slice(0, 10);
  const out: Recommendation[] = [];

  for (const trigger of TRIGGERS) {
    const node = nodes.find(
      (n) => n.quantitative && n.totalDelayMin >= trigger.thresholdMin,
    );
    if (!node) continue;

    const deadlineMinutes =
      isoToMinutes(node.flight.scheduledDeparture) - trigger.leadTimeMin;

    out.push({
      id: `${trigger.category}-${node.flight.id}`,
      category: trigger.category,
      title: trigger.title(node),
      reason: trigger.reason(node),
      deadline: minutesToIso(datePart, deadlineMinutes),
      priority: trigger.priority,
      triggeredAtHop: node.hop,
      flightNumber: node.flight.flightNumber,
      station: node.flight.origin,
    });
  }

  return out.sort((a, b) => a.deadline.localeCompare(b.deadline));
}

/**
 * The delay the primary risk model expects this flight to incur, used to seed
 * the cascade explorer when opened from the briefing. Deterministic.
 */
export function observedDelayForFlight(flight: Flight): number {
  const base = 12 + flight.riskScore * 0.55;
  const jitter = unitFromKey(`observed:${flight.id}`) * 16 - 8;
  return Math.max(6, Math.round(base + jitter));
}
